---
- name:                Corel Ansible installation
  hosts:               all
  become:              true
  become_method:       sudo
  become_user:         root
  tasks:
    - import_role:
        name:          pandemonium1986.ansible
      vars:
        ansible_users:
          - vagrant
