---
- src:     pandemonium1986.ansible
  version: 2.3.1
- src:     pandemonium1986.pip
  version: 2.1.0
- src:     pandemonium1986.init
  version: 2.4.1
- src:     pandemonium1986.ohmyzsh
  version: 2.3.0
- src:     geerlingguy.docker
  version: 2.8.1
